title: Button
description: >
    A recursive, universal build system.
baseurl: "/button"
url: "https://jasonwhite.github.io" # the base hostname & protocol for your site
github: "https://github.com/jasonwhite/button"

permalink: /:path/:basename

collections:
    docs:
        output: true

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: doc
      category: intro

markdown: kramdown
